#ifndef VERSIONINFO_H
#define VERSIONINFO_H

//#define BUILD_TIMESTAMP "@BUILD_TIMESTAMP@"
//#define CLIENT_VERSION  "@CLIENT_VERSION@"

#define BUILD_TIMESTAMP "ffffffff"
#define CLIENT_VERSION  "12345678"



#endif /* VERSIONINFO_H */
